=== Smallowl123/smallowl321.github.io/Day.dtd
<!ELEMENT Day (day*)>
<!ELEMENT day (date, maxTemperature, minTemperature, w_Event)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT maxTemperature (#PCDATA)>
<!ELEMENT minTemperature (#PCDATA)>
<!ELEMENT w_Event (#PCDATA)>

=== Smallowl123/smallowl321.github.io/Days.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE Day SYSTEM "Day.dtd">
<Day>
    <day>
        <date>2020-10-24</date>
        <maxTemperature>14</maxTemperature>
        <minTemperature>4</minTemperature>
        <w_Event>Scattered showers</w_Event>
    </day>
    <day>
        <date>2020-10-25</date>
        <maxTemperature>9</maxTemperature>
        <minTemperature>2</minTemperature>
        <w_Event>Rain</w_Event>
    </day>

    <day>
        <date>2020-10-26</date>
        <maxTemperature>6</maxTemperature>
        <minTemperature>-2</minTemperature>
        <w_Event>Partly cloudy</w_Event>
    </day>
</Day>
